gesdinet_jwt_refresh_token:
  path:     /api/token/refresh
  defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

api_login_check:
  path: /api/login_check
  methods:  [POST]

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
